# Generated by Django 2.2.7 on 2020-10-07 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_surbey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='surbey',
            new_name='survey',
        ),
    ]
